
"""
Triangle, pentagonal, and hexagonal numbers are generated by the
following formulae:
Triangle    n(n+1)/2
Pentagonal  n(3n-1)/2
Hexagonal   n(2n-1)

t285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""

def hexagonal(n):
    return n * (2 * n - 1)

def inv_pent(k):
    under = ((24 * k) + 1) ** 0.5
    if int(under) != under:
        return False
    answer = (under + 1) / 6
    if int(answer) != answer:
        return False
    else:
        return int(answer)

def inv_tri(k):
    under = ((8 * k) + 1) ** 0.5
    if int(under) != under:
        return False
    answer = (under - 1) / 2
    if int(answer) != answer:
        return False
    else:
        return int(answer)

index = 144
done = False
while done == False:
    if inv_pent(hexagonal(index)) and inv_tri(hexagonal(index)):
        done = True
    else:
        index += 1

print hexagonal(index), index
print inv_pent(hexagonal(index)), inv_tri(hexagonal(index))
                 
#print hexagonal(143), inv_tri(hexagonal(143)), inv_pent(hexagonal(143))
